version: "3.8"

services:
  db:
    logging:
      driver: none
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  server:
    volumes:
      - ./server:/app:cached
    environment:
      PORT: 6969
      DATABASE_URL: "postgresql://menyu:menyu@db/menyu_db"
    build: ./server
    ports:
      - 6969:6969
      - 4200:4200
    depends_on:
      - "db"
    command: "yarn dev"
